**Creating ndarray**

In [0]:
import numpy as np
data1=[1,3,2.5,-2,1]
arr1=np.array(data1)
arr1

array([ 1. ,  3. ,  2.5, -2. ,  1. ])

**Using a tuple to initialize ndarray**

In [0]:
data2=(1,3,2.5,-2,1)
arr2=np.array(data2)
arr2

array([ 1. ,  3. ,  2.5, -2. ,  1. ])

**Using an array to initialize ndarray**

In [0]:
arr3=np.array(arr1)
arr3

array([ 1. ,  3. ,  2.5, -2. ,  1. ])

**Dimension and Shape**

In [0]:
arr3

array([ 1. ,  3. ,  2.5, -2. ,  1. ])

In [0]:
arr1.ndim

1

In [0]:
arr1.shape

(5,)

**2-d ndarray example**

In [0]:
data2=[[1,2,3,4],[5,6,7,8]]
arr4=np.array(data2)
arr4

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [0]:
arr4.ndim

2

In [0]:
arr4.shape

(2, 4)

In [0]:
arr4.dtype

dtype('int64')

**Alternative ways to create ndarrays**

In [0]:
np.zeros(5) #a row of 5 zeros

array([0., 0., 0., 0., 0.])

In [0]:
np.ones((2,3))#2 rows 3 columns of 1’s

array([[1., 1., 1.],
       [1., 1., 1.]])

**Creating ndarrays using asarrays**

In [0]:
arr=[1,2,3,4,5]
aarray = np.array(arr)
aarray

array([1, 2, 3, 4, 5])

In [0]:
barray = np.asarray(aarray) #asarray does not create a copy
barray[1]=6
barray

array([1, 6, 3, 4, 5])

In [0]:
aarray

array([1, 6, 3, 4, 5])

In [0]:
arr

[1, 2, 3, 4, 5]

**zeros_like and ones_like**

In [0]:
aarray

array([1, 6, 3, 4, 5])

In [0]:
onearray=np.ones_like(aarray)
onearray

array([1, 1, 1, 1, 1])

In [0]:
zeroarray=np.zeros_like(aarray)
zeroarray

array([0, 0, 0, 0, 0])

**Data types for ndarrays**

In [0]:
arr1=np.array([1, 2, 3], dtype=np.int32)
arr1.dtype

dtype('int32')

**ndarray data type casting**

In [0]:
arr1.dtype

dtype('int32')

In [0]:
arr2=arr1.astype(np.float64)

In [0]:
arr2

array([1., 2., 3.])

In [0]:
arr2.dtype

dtype('float64')

In [0]:
#asarry creates new array

In [0]:
arr4

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [0]:
arr3

array([ 1. ,  3. ,  2.5, -2. ,  1. ])

In [0]:
arr4.astype(arr3.dtype)

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

**Operations:ndarrays and scalars**

Vectorization: batch operations on
arrays without having to loop through

Arithmetic operations on equal-sized
arrays applies the operation element
wise

In [0]:
array1=np.array([[1,2,3,4],[5,6,7,8]])
2*array1

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [0]:
array1+array1+array1

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24]])

In [0]:
array1-array1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [0]:
array1*2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [0]:
1/array1

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.2       , 0.16666667, 0.14285714, 0.125     ]])

In [0]:
array1**2

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

**ndarrays: indexing and slicing**

1-d array slicing and indexing is similar to Python lists

In [0]:
arr1=[1,2,3,4,5,6]
arr1

[1, 2, 3, 4, 5, 6]

In [0]:
arr1[5]

6

In [0]:
#Here arr1 is a list

Slicing on arrays:

In [0]:
arr1=np.array([1,2,5,6,4,3])
arr1

array([1, 2, 5, 6, 4, 3])

In [0]:
arr1[3]

6

In [0]:
arr1[2:4]

array([5, 6])

In [0]:
arr1[2:]

array([5, 6, 4, 3])

In [0]:
arr1[2:4]=99
arr1

array([ 1,  2, 99, 99,  4,  3])

Slicing in ndarrays is different from Python
lists in that data is not copied.
Slices are views on the original array!

In [0]:
arr2=arr1[2:4]
arr2[0]=88
arr1

array([ 1,  2, 88, 99,  4,  3])

**Higher dimensional ndarrays**

In [0]:
array34=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
array34

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [0]:
array34[1]

array([5, 6, 7, 8])

In [0]:
array34[:,2]

array([ 3,  7, 11])

Scalars as well as arrays can be
assigned to a row

In [0]:
array34[2]=99
array34

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [99, 99, 99, 99]])

In [0]:
array2=np.array([15,16,17,18])
array34[1]=array2
array34

array([[ 1,  2,  3,  4],
       [15, 16, 17, 18],
       [99, 99, 99, 99]])

In [0]:
array223=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
array223

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [0]:
array223[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [0]:
array223[1,0]

array([7, 8, 9])

In [0]:
array223[1,0,1:]

array([8, 9])

In [0]:
array223[:,1,1]

array([ 5, 11])

In [0]:
array223[...,1]

array([[ 2,  5],
       [ 8, 11]])

In [0]:
array223[...,1,1]

array([ 5, 11])

**Boolean Indexing**

In [0]:
names=np.array(['A','B','A','D','Z','C'])
names

array(['A', 'B', 'A', 'D', 'Z', 'C'], dtype='<U1')

In [0]:
alog=names=='A'
alog

array([ True, False,  True, False, False, False])

In [0]:
array34=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
array34

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [0]:
array34[alog]

array([[1, 2],
       [5, 6]])

Boolean indices may be combined
with slice indices or integer indices

In [0]:
array34[alog,1]

array([2, 6])

In [0]:
array34[alog,0:]

array([[1, 2],
       [5, 6]])

In [0]:
array34[names!='A']

array([[ 3,  4],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [0]:
array34[~(names=='A')]

array([[ 3,  4],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

Boolean conditions may be combined
with logical OR (|) or logical AND (&)

In [0]:
blog=(names=='A')|(names=='C')
array34[blog]

array([[ 1,  2],
       [ 5,  6],
       [11, 12]])

In [0]:
array34[names=='A']=99
array34

array([[99, 99],
       [ 3,  4],
       [99, 99],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [0]:
array34[array34>90]=100
array34

array([[100, 100],
       [  3,   4],
       [100, 100],
       [  7,   8],
       [  9,  10],
       [ 11,  12]])